/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IWorldCupEventHubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "logMatchCreated"
      | "logMatchFinalized"
      | "logPlatformFeeTransferred"
      | "logVotePlaced"
      | "logWinningsWithdrawn"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "logMatchCreated",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logMatchFinalized",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logPlatformFeeTransferred",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logVotePlaced",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "logWinningsWithdrawn",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "logMatchCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logMatchFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logPlatformFeeTransferred",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logVotePlaced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logWinningsWithdrawn",
    data: BytesLike
  ): Result;
}

export interface IWorldCupEventHub extends BaseContract {
  connect(runner?: ContractRunner | null): IWorldCupEventHub;
  waitForDeployment(): Promise<this>;

  interface: IWorldCupEventHubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  logMatchCreated: TypedContractMethod<
    [team1Name: string, team2Name: string, matchStartTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  logMatchFinalized: TypedContractMethod<
    [
      winningTeam: BigNumberish,
      team1TotalETH: BigNumberish,
      team2TotalETH: BigNumberish,
      totalPrizePool: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  logPlatformFeeTransferred: TypedContractMethod<
    [platformAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  logVotePlaced: TypedContractMethod<
    [
      voter: AddressLike,
      teamIndex: BigNumberish,
      voteCount: BigNumberish,
      totalCost: BigNumberish,
      platformFee: BigNumberish,
      prizePoolAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  logWinningsWithdrawn: TypedContractMethod<
    [voter: AddressLike, amount: BigNumberish, voteCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "logMatchCreated"
  ): TypedContractMethod<
    [team1Name: string, team2Name: string, matchStartTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logMatchFinalized"
  ): TypedContractMethod<
    [
      winningTeam: BigNumberish,
      team1TotalETH: BigNumberish,
      team2TotalETH: BigNumberish,
      totalPrizePool: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logPlatformFeeTransferred"
  ): TypedContractMethod<
    [platformAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logVotePlaced"
  ): TypedContractMethod<
    [
      voter: AddressLike,
      teamIndex: BigNumberish,
      voteCount: BigNumberish,
      totalCost: BigNumberish,
      platformFee: BigNumberish,
      prizePoolAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logWinningsWithdrawn"
  ): TypedContractMethod<
    [voter: AddressLike, amount: BigNumberish, voteCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
