/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface WorldCupMatchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_PRICE"
      | "LINEAR_INCREMENT"
      | "MAX_FEE_PERCENT"
      | "MAX_VOTES_PER_TX"
      | "PHASE_1_DURATION"
      | "REFERRAL_FEE_BPS"
      | "TOTAL_VOTING_DURATION"
      | "calculateVotePrice"
      | "calculateVotePriceAt"
      | "calculateWinnings"
      | "eventHub"
      | "getCurrentPhase"
      | "getMatchDetails"
      | "getPhase1Details"
      | "getTotalPrizePool"
      | "getUserVoteStats"
      | "getVoterCount"
      | "hasVoted"
      | "hasWithdrawn"
      | "matchEndTime"
      | "matchFinalized"
      | "matchStartTime"
      | "owner"
      | "pause"
      | "paused"
      | "phase1Ended"
      | "platformAddress"
      | "platformFeePercent"
      | "referrerEarnings"
      | "renounceOwnership"
      | "setPlatformAddress"
      | "setPlatformFee"
      | "team1Name"
      | "team1Phase1Votes"
      | "team1TotalETH"
      | "team1VoteCount"
      | "team2Name"
      | "team2Phase1Votes"
      | "team2TotalETH"
      | "team2VoteCount"
      | "totalPlatformFeesCollected"
      | "transferOwnership"
      | "unpause"
      | "userETH"
      | "userVoteCount"
      | "vote"
      | "voters"
      | "votingEndTime"
      | "winningTeam"
      | "withdrawWinnings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchFinalized"
      | "OwnershipTransferred"
      | "Paused"
      | "PlatformAddressUpdated"
      | "PlatformFeeTransferred"
      | "PlatformFeeUpdated"
      | "ReferralPaid"
      | "Unpaused"
      | "VotesPlaced"
      | "WinningsWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LINEAR_INCREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VOTES_PER_TX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PHASE_1_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFERRAL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_VOTING_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateVotePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateVotePriceAt",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateWinnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "eventHub", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrentPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPhase1Details",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPrizePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVoteStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasWithdrawn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matchEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matchFinalized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matchStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "phase1Ended",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referrerEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "team1Name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "team1Phase1Votes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "team1TotalETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "team1VoteCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "team2Name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "team2Phase1Votes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "team2TotalETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "team2VoteCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlatformFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userETH",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userVoteCount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votingEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "winningTeam",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawWinnings",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "BASE_PRICE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LINEAR_INCREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VOTES_PER_TX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PHASE_1_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFERRAL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_VOTING_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateVotePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateVotePriceAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eventHub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPhase1Details",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPrizePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVoteStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoterCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "phase1Ended",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referrerEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "team1Name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "team1Phase1Votes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "team1TotalETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "team1VoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "team2Name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "team2Phase1Votes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "team2TotalETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "team2VoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPlatformFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winningTeam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawWinnings",
    data: BytesLike
  ): Result;
}

export namespace MatchFinalizedEvent {
  export type InputTuple = [
    winningTeam: BigNumberish,
    team1Total: BigNumberish,
    team2Total: BigNumberish
  ];
  export type OutputTuple = [
    winningTeam: bigint,
    team1Total: bigint,
    team2Total: bigint
  ];
  export interface OutputObject {
    winningTeam: bigint;
    team1Total: bigint;
    team2Total: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformAddressUpdatedEvent {
  export type InputTuple = [newPlatform: AddressLike];
  export type OutputTuple = [newPlatform: string];
  export interface OutputObject {
    newPlatform: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeTransferredEvent {
  export type InputTuple = [platform: AddressLike, amount: BigNumberish];
  export type OutputTuple = [platform: string, amount: bigint];
  export interface OutputObject {
    platform: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFeePercent: BigNumberish];
  export type OutputTuple = [newFeePercent: bigint];
  export interface OutputObject {
    newFeePercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralPaidEvent {
  export type InputTuple = [
    referrer: AddressLike,
    voter: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [referrer: string, voter: string, amount: bigint];
  export interface OutputObject {
    referrer: string;
    voter: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotesPlacedEvent {
  export type InputTuple = [
    voter: AddressLike,
    teamIndex: BigNumberish,
    voteCount: BigNumberish,
    totalCost: BigNumberish,
    platformFee: BigNumberish,
    prizePoolAmount: BigNumberish
  ];
  export type OutputTuple = [
    voter: string,
    teamIndex: bigint,
    voteCount: bigint,
    totalCost: bigint,
    platformFee: bigint,
    prizePoolAmount: bigint
  ];
  export interface OutputObject {
    voter: string;
    teamIndex: bigint;
    voteCount: bigint;
    totalCost: bigint;
    platformFee: bigint;
    prizePoolAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsWithdrawnEvent {
  export type InputTuple = [
    voter: AddressLike,
    amount: BigNumberish,
    voteCount: BigNumberish
  ];
  export type OutputTuple = [voter: string, amount: bigint, voteCount: bigint];
  export interface OutputObject {
    voter: string;
    amount: bigint;
    voteCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorldCupMatch extends BaseContract {
  connect(runner?: ContractRunner | null): WorldCupMatch;
  waitForDeployment(): Promise<this>;

  interface: WorldCupMatchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_PRICE: TypedContractMethod<[], [bigint], "view">;

  LINEAR_INCREMENT: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  MAX_VOTES_PER_TX: TypedContractMethod<[], [bigint], "view">;

  PHASE_1_DURATION: TypedContractMethod<[], [bigint], "view">;

  REFERRAL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  TOTAL_VOTING_DURATION: TypedContractMethod<[], [bigint], "view">;

  calculateVotePrice: TypedContractMethod<
    [teamIndex: BigNumberish],
    [bigint],
    "view"
  >;

  calculateVotePriceAt: TypedContractMethod<
    [teamIndex: BigNumberish, atVoteCount: BigNumberish],
    [bigint],
    "view"
  >;

  calculateWinnings: TypedContractMethod<
    [voter: AddressLike],
    [bigint],
    "view"
  >;

  eventHub: TypedContractMethod<[], [string], "view">;

  getCurrentPhase: TypedContractMethod<[], [bigint], "view">;

  getMatchDetails: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        _team1Name: string;
        _team2Name: string;
        _team1Votes: bigint;
        _team2Votes: bigint;
        _team1ETH: bigint;
        _team2ETH: bigint;
        _totalPrizePool: bigint;
        _totalPlatformFees: bigint;
        _currentPhase: bigint;
        _isFinalized: boolean;
        _winner: string;
      }
    ],
    "view"
  >;

  getPhase1Details: TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean] & {
        team1Votes: bigint;
        team2Votes: bigint;
        ended: boolean;
      }
    ],
    "view"
  >;

  getTotalPrizePool: TypedContractMethod<[], [bigint], "view">;

  getUserVoteStats: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        team1Votes: bigint;
        team2Votes: bigint;
        team1ETH: bigint;
        team2ETH: bigint;
        potentialWinnings: bigint;
      }
    ],
    "view"
  >;

  getVoterCount: TypedContractMethod<[], [bigint], "view">;

  hasVoted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasWithdrawn: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  matchEndTime: TypedContractMethod<[], [bigint], "view">;

  matchFinalized: TypedContractMethod<[], [boolean], "view">;

  matchStartTime: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  phase1Ended: TypedContractMethod<[], [boolean], "view">;

  platformAddress: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  referrerEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPlatformAddress: TypedContractMethod<
    [newPlatform: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  team1Name: TypedContractMethod<[], [string], "view">;

  team1Phase1Votes: TypedContractMethod<[], [bigint], "view">;

  team1TotalETH: TypedContractMethod<[], [bigint], "view">;

  team1VoteCount: TypedContractMethod<[], [bigint], "view">;

  team2Name: TypedContractMethod<[], [string], "view">;

  team2Phase1Votes: TypedContractMethod<[], [bigint], "view">;

  team2TotalETH: TypedContractMethod<[], [bigint], "view">;

  team2VoteCount: TypedContractMethod<[], [bigint], "view">;

  totalPlatformFeesCollected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userETH: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userVoteCount: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  vote: TypedContractMethod<
    [teamIndex: BigNumberish, numVotes: BigNumberish, referrer: AddressLike],
    [void],
    "payable"
  >;

  voters: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  votingEndTime: TypedContractMethod<[], [bigint], "view">;

  winningTeam: TypedContractMethod<[], [bigint], "view">;

  withdrawWinnings: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LINEAR_INCREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_VOTES_PER_TX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PHASE_1_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRAL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_VOTING_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateVotePrice"
  ): TypedContractMethod<[teamIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateVotePriceAt"
  ): TypedContractMethod<
    [teamIndex: BigNumberish, atVoteCount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateWinnings"
  ): TypedContractMethod<[voter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "eventHub"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentPhase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMatchDetails"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        _team1Name: string;
        _team2Name: string;
        _team1Votes: bigint;
        _team2Votes: bigint;
        _team1ETH: bigint;
        _team2ETH: bigint;
        _totalPrizePool: bigint;
        _totalPlatformFees: bigint;
        _currentPhase: bigint;
        _isFinalized: boolean;
        _winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPhase1Details"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean] & {
        team1Votes: bigint;
        team2Votes: bigint;
        ended: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPrizePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserVoteStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        team1Votes: bigint;
        team2Votes: bigint;
        team1ETH: bigint;
        team2ETH: bigint;
        potentialWinnings: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoterCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasWithdrawn"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "matchEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matchFinalized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "matchStartTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "phase1Ended"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "referrerEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformAddress"
  ): TypedContractMethod<[newPlatform: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFeePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "team1Name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "team1Phase1Votes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "team1TotalETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "team1VoteCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "team2Name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "team2Phase1Votes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "team2TotalETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "team2VoteCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPlatformFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userETH"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userVoteCount"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [teamIndex: BigNumberish, numVotes: BigNumberish, referrer: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "voters"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "votingEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "winningTeam"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawWinnings"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "MatchFinalized"
  ): TypedContractEvent<
    MatchFinalizedEvent.InputTuple,
    MatchFinalizedEvent.OutputTuple,
    MatchFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformAddressUpdated"
  ): TypedContractEvent<
    PlatformAddressUpdatedEvent.InputTuple,
    PlatformAddressUpdatedEvent.OutputTuple,
    PlatformAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeTransferred"
  ): TypedContractEvent<
    PlatformFeeTransferredEvent.InputTuple,
    PlatformFeeTransferredEvent.OutputTuple,
    PlatformFeeTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralPaid"
  ): TypedContractEvent<
    ReferralPaidEvent.InputTuple,
    ReferralPaidEvent.OutputTuple,
    ReferralPaidEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VotesPlaced"
  ): TypedContractEvent<
    VotesPlacedEvent.InputTuple,
    VotesPlacedEvent.OutputTuple,
    VotesPlacedEvent.OutputObject
  >;
  getEvent(
    key: "WinningsWithdrawn"
  ): TypedContractEvent<
    WinningsWithdrawnEvent.InputTuple,
    WinningsWithdrawnEvent.OutputTuple,
    WinningsWithdrawnEvent.OutputObject
  >;

  filters: {
    "MatchFinalized(uint8,uint256,uint256)": TypedContractEvent<
      MatchFinalizedEvent.InputTuple,
      MatchFinalizedEvent.OutputTuple,
      MatchFinalizedEvent.OutputObject
    >;
    MatchFinalized: TypedContractEvent<
      MatchFinalizedEvent.InputTuple,
      MatchFinalizedEvent.OutputTuple,
      MatchFinalizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused()": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformAddressUpdated(address)": TypedContractEvent<
      PlatformAddressUpdatedEvent.InputTuple,
      PlatformAddressUpdatedEvent.OutputTuple,
      PlatformAddressUpdatedEvent.OutputObject
    >;
    PlatformAddressUpdated: TypedContractEvent<
      PlatformAddressUpdatedEvent.InputTuple,
      PlatformAddressUpdatedEvent.OutputTuple,
      PlatformAddressUpdatedEvent.OutputObject
    >;

    "PlatformFeeTransferred(address,uint256)": TypedContractEvent<
      PlatformFeeTransferredEvent.InputTuple,
      PlatformFeeTransferredEvent.OutputTuple,
      PlatformFeeTransferredEvent.OutputObject
    >;
    PlatformFeeTransferred: TypedContractEvent<
      PlatformFeeTransferredEvent.InputTuple,
      PlatformFeeTransferredEvent.OutputTuple,
      PlatformFeeTransferredEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "ReferralPaid(address,address,uint256)": TypedContractEvent<
      ReferralPaidEvent.InputTuple,
      ReferralPaidEvent.OutputTuple,
      ReferralPaidEvent.OutputObject
    >;
    ReferralPaid: TypedContractEvent<
      ReferralPaidEvent.InputTuple,
      ReferralPaidEvent.OutputTuple,
      ReferralPaidEvent.OutputObject
    >;

    "Unpaused()": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VotesPlaced(address,uint8,uint256,uint256,uint256,uint256)": TypedContractEvent<
      VotesPlacedEvent.InputTuple,
      VotesPlacedEvent.OutputTuple,
      VotesPlacedEvent.OutputObject
    >;
    VotesPlaced: TypedContractEvent<
      VotesPlacedEvent.InputTuple,
      VotesPlacedEvent.OutputTuple,
      VotesPlacedEvent.OutputObject
    >;

    "WinningsWithdrawn(address,uint256,uint256)": TypedContractEvent<
      WinningsWithdrawnEvent.InputTuple,
      WinningsWithdrawnEvent.OutputTuple,
      WinningsWithdrawnEvent.OutputObject
    >;
    WinningsWithdrawn: TypedContractEvent<
      WinningsWithdrawnEvent.InputTuple,
      WinningsWithdrawnEvent.OutputTuple,
      WinningsWithdrawnEvent.OutputObject
    >;
  };
}
