/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as worldCupMatchSol from "./WorldCupMatch.sol";
export type { worldCupMatchSol };
import type * as worldCupMatchFactorySol from "./WorldCupMatchFactory.sol";
export type { worldCupMatchFactorySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
export type { AchievementNFT } from "./AchievementNFT";
export type { MatchNFT } from "./MatchNFT";
export type { WorldCupEventHub } from "./WorldCupEventHub";
export type { WorldCupNFT } from "./WorldCupNFT";
export type { WorldCupQualification } from "./WorldCupQualification";
