/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as worldCupMatchSol from "./WorldCupMatch.sol";
export type { worldCupMatchSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { WorldCupEventHub } from "./WorldCupEventHub";
export type { WorldCupNFT } from "./WorldCupNFT";
export type { WorldCupQualification } from "./WorldCupQualification";
