/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WorldCupQualificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_PRICE"
      | "MAX_PLATFORM_FEE_BPS"
      | "MAX_VOTES_PER_TX"
      | "PRICE_INCREMENT"
      | "QUALIFICATION_SPOTS"
      | "addCountries"
      | "addCountry"
      | "allCountries"
      | "calculateVoteCost"
      | "claim"
      | "claimable"
      | "countryETH"
      | "countryVotes"
      | "ethForCountry"
      | "feeRecipient"
      | "finalizeQualification"
      | "getETHPerCountry"
      | "getPlatformFeeAmount"
      | "getQualificationDetails"
      | "getTotalPrizePool"
      | "getUserVotes"
      | "hasClaimed"
      | "isQualified"
      | "owner"
      | "platformFeeBps"
      | "qualificationEndTime"
      | "qualificationFinalized"
      | "removeCountry"
      | "renounceOwnership"
      | "setPlatformFee"
      | "totalETHCollected"
      | "totalPlatformFees"
      | "totalPrizePool"
      | "totalQualifiedVotes"
      | "totalVotes"
      | "transferOwnership"
      | "userVotes"
      | "validCountry"
      | "vote"
      | "votePrice"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CountryAdded"
      | "CountryRemoved"
      | "OwnershipTransferred"
      | "PlatformFeeUpdated"
      | "PlatformFeesWithdrawn"
      | "PrizesDistributed"
      | "QualificationEnded"
      | "QualificationFinalized"
      | "VotePlaced"
      | "Voted"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VOTES_PER_TX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_INCREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUALIFICATION_SPOTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCountries",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addCountry",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allCountries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateVoteCost",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "countryETH",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "countryVotes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ethForCountry",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeQualification",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getETHPerCountry",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformFeeAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQualificationDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPrizePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVotes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isQualified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "qualificationEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "qualificationFinalized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeCountry",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalETHCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlatformFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPrizePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalQualifiedVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userVotes",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validCountry",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votePrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "BASE_PRICE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VOTES_PER_TX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_INCREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUALIFICATION_SPOTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addCountry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateVoteCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "countryETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "countryVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethForCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeQualification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getETHPerCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformFeeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQualificationDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPrizePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isQualified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "qualificationEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "qualificationFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalETHCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPlatformFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPrizePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalQualifiedVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votePrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace CountryAddedEvent {
  export type InputTuple = [country: BytesLike];
  export type OutputTuple = [country: string];
  export interface OutputObject {
    country: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryRemovedEvent {
  export type InputTuple = [country: BytesLike];
  export type OutputTuple = [country: string];
  export interface OutputObject {
    country: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [oldFeeBps: BigNumberish, newFeeBps: BigNumberish];
  export type OutputTuple = [oldFeeBps: bigint, newFeeBps: bigint];
  export interface OutputObject {
    oldFeeBps: bigint;
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeesWithdrawnEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizesDistributedEvent {
  export type InputTuple = [totalPrizePool: BigNumberish];
  export type OutputTuple = [totalPrizePool: bigint];
  export interface OutputObject {
    totalPrizePool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QualificationEndedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QualificationFinalizedEvent {
  export type InputTuple = [qualifiedCountries: BytesLike[]];
  export type OutputTuple = [qualifiedCountries: string[]];
  export interface OutputObject {
    qualifiedCountries: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotePlacedEvent {
  export type InputTuple = [
    voter: AddressLike,
    country: BytesLike,
    votes: BigNumberish,
    cost: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    voter: string,
    country: string,
    votes: bigint,
    cost: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    voter: string;
    country: string;
    votes: bigint;
    cost: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    user: AddressLike,
    country: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, country: string, amount: bigint];
  export interface OutputObject {
    user: string;
    country: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorldCupQualification extends BaseContract {
  connect(runner?: ContractRunner | null): WorldCupQualification;
  waitForDeployment(): Promise<this>;

  interface: WorldCupQualificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_PRICE: TypedContractMethod<[], [bigint], "view">;

  MAX_PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_VOTES_PER_TX: TypedContractMethod<[], [bigint], "view">;

  PRICE_INCREMENT: TypedContractMethod<[], [bigint], "view">;

  QUALIFICATION_SPOTS: TypedContractMethod<[], [bigint], "view">;

  addCountries: TypedContractMethod<
    [countries: BytesLike[]],
    [void],
    "nonpayable"
  >;

  addCountry: TypedContractMethod<[country: BytesLike], [void], "nonpayable">;

  allCountries: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  calculateVoteCost: TypedContractMethod<
    [country: BytesLike, votes: BigNumberish],
    [bigint],
    "view"
  >;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  claimable: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  countryETH: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  countryVotes: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  ethForCountry: TypedContractMethod<[country: BytesLike], [bigint], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  finalizeQualification: TypedContractMethod<
    [qualifiedCountries: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getETHPerCountry: TypedContractMethod<[country: BytesLike], [bigint], "view">;

  getPlatformFeeAmount: TypedContractMethod<[], [bigint], "view">;

  getQualificationDetails: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, bigint] & {
        _totalPrizePool: bigint;
        _qualificationEndTime: bigint;
        _qualificationSpots: bigint;
        _isFinalized: boolean;
        _totalVoters: bigint;
      }
    ],
    "view"
  >;

  getTotalPrizePool: TypedContractMethod<[], [bigint], "view">;

  getUserVotes: TypedContractMethod<
    [user: AddressLike],
    [[string[], bigint[]] & { countries: string[]; votes: bigint[] }],
    "view"
  >;

  hasClaimed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isQualified: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  qualificationEndTime: TypedContractMethod<[], [bigint], "view">;

  qualificationFinalized: TypedContractMethod<[], [boolean], "view">;

  removeCountry: TypedContractMethod<
    [country: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPlatformFee: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalETHCollected: TypedContractMethod<[], [bigint], "view">;

  totalPlatformFees: TypedContractMethod<[], [bigint], "view">;

  totalPrizePool: TypedContractMethod<[], [bigint], "view">;

  totalQualifiedVotes: TypedContractMethod<[], [bigint], "view">;

  totalVotes: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userVotes: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  validCountry: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  vote: TypedContractMethod<
    [country: BytesLike, votes: BigNumberish],
    [void],
    "payable"
  >;

  votePrice: TypedContractMethod<[country: BytesLike], [bigint], "view">;

  withdrawPlatformFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_VOTES_PER_TX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_INCREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUALIFICATION_SPOTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addCountries"
  ): TypedContractMethod<[countries: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addCountry"
  ): TypedContractMethod<[country: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allCountries"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "calculateVoteCost"
  ): TypedContractMethod<
    [country: BytesLike, votes: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimable"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "countryETH"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "countryVotes"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "ethForCountry"
  ): TypedContractMethod<[country: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeQualification"
  ): TypedContractMethod<
    [qualifiedCountries: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getETHPerCountry"
  ): TypedContractMethod<[country: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlatformFeeAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQualificationDetails"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, bigint] & {
        _totalPrizePool: bigint;
        _qualificationEndTime: bigint;
        _qualificationSpots: bigint;
        _isFinalized: boolean;
        _totalVoters: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPrizePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserVotes"
  ): TypedContractMethod<
    [user: AddressLike],
    [[string[], bigint[]] & { countries: string[]; votes: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isQualified"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "qualificationEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "qualificationFinalized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeCountry"
  ): TypedContractMethod<[country: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalETHCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPlatformFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPrizePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalQualifiedVotes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVotes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userVotes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "validCountry"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [country: BytesLike, votes: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "votePrice"
  ): TypedContractMethod<[country: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CountryAdded"
  ): TypedContractEvent<
    CountryAddedEvent.InputTuple,
    CountryAddedEvent.OutputTuple,
    CountryAddedEvent.OutputObject
  >;
  getEvent(
    key: "CountryRemoved"
  ): TypedContractEvent<
    CountryRemovedEvent.InputTuple,
    CountryRemovedEvent.OutputTuple,
    CountryRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeesWithdrawn"
  ): TypedContractEvent<
    PlatformFeesWithdrawnEvent.InputTuple,
    PlatformFeesWithdrawnEvent.OutputTuple,
    PlatformFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "PrizesDistributed"
  ): TypedContractEvent<
    PrizesDistributedEvent.InputTuple,
    PrizesDistributedEvent.OutputTuple,
    PrizesDistributedEvent.OutputObject
  >;
  getEvent(
    key: "QualificationEnded"
  ): TypedContractEvent<
    QualificationEndedEvent.InputTuple,
    QualificationEndedEvent.OutputTuple,
    QualificationEndedEvent.OutputObject
  >;
  getEvent(
    key: "QualificationFinalized"
  ): TypedContractEvent<
    QualificationFinalizedEvent.InputTuple,
    QualificationFinalizedEvent.OutputTuple,
    QualificationFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "VotePlaced"
  ): TypedContractEvent<
    VotePlacedEvent.InputTuple,
    VotePlacedEvent.OutputTuple,
    VotePlacedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "CountryAdded(bytes2)": TypedContractEvent<
      CountryAddedEvent.InputTuple,
      CountryAddedEvent.OutputTuple,
      CountryAddedEvent.OutputObject
    >;
    CountryAdded: TypedContractEvent<
      CountryAddedEvent.InputTuple,
      CountryAddedEvent.OutputTuple,
      CountryAddedEvent.OutputObject
    >;

    "CountryRemoved(bytes2)": TypedContractEvent<
      CountryRemovedEvent.InputTuple,
      CountryRemovedEvent.OutputTuple,
      CountryRemovedEvent.OutputObject
    >;
    CountryRemoved: TypedContractEvent<
      CountryRemovedEvent.InputTuple,
      CountryRemovedEvent.OutputTuple,
      CountryRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256,uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "PlatformFeesWithdrawn(uint256)": TypedContractEvent<
      PlatformFeesWithdrawnEvent.InputTuple,
      PlatformFeesWithdrawnEvent.OutputTuple,
      PlatformFeesWithdrawnEvent.OutputObject
    >;
    PlatformFeesWithdrawn: TypedContractEvent<
      PlatformFeesWithdrawnEvent.InputTuple,
      PlatformFeesWithdrawnEvent.OutputTuple,
      PlatformFeesWithdrawnEvent.OutputObject
    >;

    "PrizesDistributed(uint256)": TypedContractEvent<
      PrizesDistributedEvent.InputTuple,
      PrizesDistributedEvent.OutputTuple,
      PrizesDistributedEvent.OutputObject
    >;
    PrizesDistributed: TypedContractEvent<
      PrizesDistributedEvent.InputTuple,
      PrizesDistributedEvent.OutputTuple,
      PrizesDistributedEvent.OutputObject
    >;

    "QualificationEnded()": TypedContractEvent<
      QualificationEndedEvent.InputTuple,
      QualificationEndedEvent.OutputTuple,
      QualificationEndedEvent.OutputObject
    >;
    QualificationEnded: TypedContractEvent<
      QualificationEndedEvent.InputTuple,
      QualificationEndedEvent.OutputTuple,
      QualificationEndedEvent.OutputObject
    >;

    "QualificationFinalized(bytes2[])": TypedContractEvent<
      QualificationFinalizedEvent.InputTuple,
      QualificationFinalizedEvent.OutputTuple,
      QualificationFinalizedEvent.OutputObject
    >;
    QualificationFinalized: TypedContractEvent<
      QualificationFinalizedEvent.InputTuple,
      QualificationFinalizedEvent.OutputTuple,
      QualificationFinalizedEvent.OutputObject
    >;

    "VotePlaced(address,bytes2,uint256,uint256,uint256)": TypedContractEvent<
      VotePlacedEvent.InputTuple,
      VotePlacedEvent.OutputTuple,
      VotePlacedEvent.OutputObject
    >;
    VotePlaced: TypedContractEvent<
      VotePlacedEvent.InputTuple,
      VotePlacedEvent.OutputTuple,
      VotePlacedEvent.OutputObject
    >;

    "Voted(address,bytes2,uint256)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;

    "WinningsClaimed(address,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
