/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IWorldCupEventHub } from "./IWorldCupEventHub";
export type { IWorldCupMatch } from "./IWorldCupMatch";
export type { IWorldCupQualification } from "./IWorldCupQualification";
