/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IWorldCupMatchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateVotePrice"
      | "calculateVotePriceAt"
      | "calculateWinnings"
      | "getCurrentPhase"
      | "getMatchDetails"
      | "getPhase1Details"
      | "getTotalPrizePool"
      | "getUserVoteStats"
      | "getVoterCount"
      | "matchEndTime"
      | "matchFinalized"
      | "matchStartTime"
      | "platformAddress"
      | "platformFeePercent"
      | "team1Name"
      | "team1TotalETH"
      | "team1VoteCount"
      | "team2Name"
      | "team2TotalETH"
      | "team2VoteCount"
      | "totalPlatformFeesCollected"
      | "userETH"
      | "userVoteCount"
      | "vote"
      | "votingEndTime"
      | "winningTeam"
      | "withdrawWinnings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchFinalized"
      | "PlatformFeeTransferred"
      | "VotesPlaced"
      | "WinningsWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateVotePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateVotePriceAt",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateWinnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPhase1Details",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPrizePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVoteStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matchEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matchFinalized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matchStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "team1Name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "team1TotalETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "team1VoteCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "team2Name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "team2TotalETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "team2VoteCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlatformFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userETH",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userVoteCount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votingEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "winningTeam",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawWinnings",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateVotePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateVotePriceAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPhase1Details",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPrizePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVoteStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoterCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "team1Name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "team1TotalETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "team1VoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "team2Name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "team2TotalETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "team2VoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPlatformFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winningTeam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawWinnings",
    data: BytesLike
  ): Result;
}

export namespace MatchFinalizedEvent {
  export type InputTuple = [
    winningTeam: BigNumberish,
    team1Total: BigNumberish,
    team2Total: BigNumberish
  ];
  export type OutputTuple = [
    winningTeam: bigint,
    team1Total: bigint,
    team2Total: bigint
  ];
  export interface OutputObject {
    winningTeam: bigint;
    team1Total: bigint;
    team2Total: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeTransferredEvent {
  export type InputTuple = [platform: AddressLike, amount: BigNumberish];
  export type OutputTuple = [platform: string, amount: bigint];
  export interface OutputObject {
    platform: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotesPlacedEvent {
  export type InputTuple = [
    voter: AddressLike,
    teamIndex: BigNumberish,
    voteCount: BigNumberish,
    totalCost: BigNumberish,
    platformFee: BigNumberish,
    prizePoolAmount: BigNumberish
  ];
  export type OutputTuple = [
    voter: string,
    teamIndex: bigint,
    voteCount: bigint,
    totalCost: bigint,
    platformFee: bigint,
    prizePoolAmount: bigint
  ];
  export interface OutputObject {
    voter: string;
    teamIndex: bigint;
    voteCount: bigint;
    totalCost: bigint;
    platformFee: bigint;
    prizePoolAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsWithdrawnEvent {
  export type InputTuple = [
    voter: AddressLike,
    amount: BigNumberish,
    voteCount: BigNumberish
  ];
  export type OutputTuple = [voter: string, amount: bigint, voteCount: bigint];
  export interface OutputObject {
    voter: string;
    amount: bigint;
    voteCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IWorldCupMatch extends BaseContract {
  connect(runner?: ContractRunner | null): IWorldCupMatch;
  waitForDeployment(): Promise<this>;

  interface: IWorldCupMatchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateVotePrice: TypedContractMethod<
    [teamIndex: BigNumberish],
    [bigint],
    "view"
  >;

  calculateVotePriceAt: TypedContractMethod<
    [teamIndex: BigNumberish, atVoteCount: BigNumberish],
    [bigint],
    "view"
  >;

  calculateWinnings: TypedContractMethod<
    [voter: AddressLike],
    [bigint],
    "view"
  >;

  getCurrentPhase: TypedContractMethod<[], [bigint], "view">;

  getMatchDetails: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        _team1Name: string;
        _team2Name: string;
        _team1Votes: bigint;
        _team2Votes: bigint;
        _team1ETH: bigint;
        _team2ETH: bigint;
        _totalPrizePool: bigint;
        _totalPlatformFees: bigint;
        _currentPhase: bigint;
        _isFinalized: boolean;
        _winner: string;
      }
    ],
    "view"
  >;

  getPhase1Details: TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean] & {
        team1Votes: bigint;
        team2Votes: bigint;
        ended: boolean;
      }
    ],
    "view"
  >;

  getTotalPrizePool: TypedContractMethod<[], [bigint], "view">;

  getUserVoteStats: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        team1Votes: bigint;
        team2Votes: bigint;
        team1ETH: bigint;
        team2ETH: bigint;
        potentialWinnings: bigint;
      }
    ],
    "view"
  >;

  getVoterCount: TypedContractMethod<[], [bigint], "view">;

  matchEndTime: TypedContractMethod<[], [bigint], "view">;

  matchFinalized: TypedContractMethod<[], [boolean], "view">;

  matchStartTime: TypedContractMethod<[], [bigint], "view">;

  platformAddress: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  team1Name: TypedContractMethod<[], [string], "view">;

  team1TotalETH: TypedContractMethod<[], [bigint], "view">;

  team1VoteCount: TypedContractMethod<[], [bigint], "view">;

  team2Name: TypedContractMethod<[], [string], "view">;

  team2TotalETH: TypedContractMethod<[], [bigint], "view">;

  team2VoteCount: TypedContractMethod<[], [bigint], "view">;

  totalPlatformFeesCollected: TypedContractMethod<[], [bigint], "view">;

  userETH: TypedContractMethod<
    [voter: AddressLike, teamIndex: BigNumberish],
    [bigint],
    "view"
  >;

  userVoteCount: TypedContractMethod<
    [voter: AddressLike, teamIndex: BigNumberish],
    [bigint],
    "view"
  >;

  vote: TypedContractMethod<
    [teamIndex: BigNumberish, numVotes: BigNumberish],
    [void],
    "payable"
  >;

  votingEndTime: TypedContractMethod<[], [bigint], "view">;

  winningTeam: TypedContractMethod<[], [bigint], "view">;

  withdrawWinnings: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateVotePrice"
  ): TypedContractMethod<[teamIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateVotePriceAt"
  ): TypedContractMethod<
    [teamIndex: BigNumberish, atVoteCount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateWinnings"
  ): TypedContractMethod<[voter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentPhase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMatchDetails"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        _team1Name: string;
        _team2Name: string;
        _team1Votes: bigint;
        _team2Votes: bigint;
        _team1ETH: bigint;
        _team2ETH: bigint;
        _totalPrizePool: bigint;
        _totalPlatformFees: bigint;
        _currentPhase: bigint;
        _isFinalized: boolean;
        _winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPhase1Details"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean] & {
        team1Votes: bigint;
        team2Votes: bigint;
        ended: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPrizePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserVoteStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        team1Votes: bigint;
        team2Votes: bigint;
        team1ETH: bigint;
        team2ETH: bigint;
        potentialWinnings: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoterCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matchEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matchFinalized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "matchStartTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "team1Name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "team1TotalETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "team1VoteCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "team2Name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "team2TotalETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "team2VoteCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPlatformFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userETH"
  ): TypedContractMethod<
    [voter: AddressLike, teamIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userVoteCount"
  ): TypedContractMethod<
    [voter: AddressLike, teamIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [teamIndex: BigNumberish, numVotes: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "votingEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "winningTeam"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawWinnings"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "MatchFinalized"
  ): TypedContractEvent<
    MatchFinalizedEvent.InputTuple,
    MatchFinalizedEvent.OutputTuple,
    MatchFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeTransferred"
  ): TypedContractEvent<
    PlatformFeeTransferredEvent.InputTuple,
    PlatformFeeTransferredEvent.OutputTuple,
    PlatformFeeTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VotesPlaced"
  ): TypedContractEvent<
    VotesPlacedEvent.InputTuple,
    VotesPlacedEvent.OutputTuple,
    VotesPlacedEvent.OutputObject
  >;
  getEvent(
    key: "WinningsWithdrawn"
  ): TypedContractEvent<
    WinningsWithdrawnEvent.InputTuple,
    WinningsWithdrawnEvent.OutputTuple,
    WinningsWithdrawnEvent.OutputObject
  >;

  filters: {
    "MatchFinalized(uint8,uint256,uint256)": TypedContractEvent<
      MatchFinalizedEvent.InputTuple,
      MatchFinalizedEvent.OutputTuple,
      MatchFinalizedEvent.OutputObject
    >;
    MatchFinalized: TypedContractEvent<
      MatchFinalizedEvent.InputTuple,
      MatchFinalizedEvent.OutputTuple,
      MatchFinalizedEvent.OutputObject
    >;

    "PlatformFeeTransferred(address,uint256)": TypedContractEvent<
      PlatformFeeTransferredEvent.InputTuple,
      PlatformFeeTransferredEvent.OutputTuple,
      PlatformFeeTransferredEvent.OutputObject
    >;
    PlatformFeeTransferred: TypedContractEvent<
      PlatformFeeTransferredEvent.InputTuple,
      PlatformFeeTransferredEvent.OutputTuple,
      PlatformFeeTransferredEvent.OutputObject
    >;

    "VotesPlaced(address,uint8,uint256,uint256,uint256,uint256)": TypedContractEvent<
      VotesPlacedEvent.InputTuple,
      VotesPlacedEvent.OutputTuple,
      VotesPlacedEvent.OutputObject
    >;
    VotesPlaced: TypedContractEvent<
      VotesPlacedEvent.InputTuple,
      VotesPlacedEvent.OutputTuple,
      VotesPlacedEvent.OutputObject
    >;

    "WinningsWithdrawn(address,uint256,uint256)": TypedContractEvent<
      WinningsWithdrawnEvent.InputTuple,
      WinningsWithdrawnEvent.OutputTuple,
      WinningsWithdrawnEvent.OutputObject
    >;
    WinningsWithdrawn: TypedContractEvent<
      WinningsWithdrawnEvent.InputTuple,
      WinningsWithdrawnEvent.OutputTuple,
      WinningsWithdrawnEvent.OutputObject
    >;
  };
}
