/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IWorldCupEventHubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allMatches"
      | "authorizeMatch"
      | "authorizedMatches"
      | "deauthorizeMatch"
      | "getAllMatches"
      | "getMatchCount"
      | "isAuthorized"
      | "logMatchCreated"
      | "logMatchFinalized"
      | "logPlatformFeeTransferred"
      | "logVotePlaced"
      | "logWinningsWithdrawn"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GlobalMatchCreated"
      | "GlobalMatchFinalized"
      | "GlobalPlatformFeeTransferred"
      | "GlobalVotePlaced"
      | "GlobalWinningsWithdrawn"
      | "MatchAuthorized"
      | "MatchDeauthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allMatches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeMatch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedMatches",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorizeMatch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllMatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logMatchCreated",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logMatchFinalized",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logPlatformFeeTransferred",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logVotePlaced",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "logWinningsWithdrawn",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allMatches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorizeMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logMatchCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logMatchFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logPlatformFeeTransferred",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logVotePlaced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logWinningsWithdrawn",
    data: BytesLike
  ): Result;
}

export namespace GlobalMatchCreatedEvent {
  export type InputTuple = [
    matchAddress: AddressLike,
    team1Name: string,
    team2Name: string,
    matchStartTime: BigNumberish,
    matchId: BigNumberish
  ];
  export type OutputTuple = [
    matchAddress: string,
    team1Name: string,
    team2Name: string,
    matchStartTime: bigint,
    matchId: bigint
  ];
  export interface OutputObject {
    matchAddress: string;
    team1Name: string;
    team2Name: string;
    matchStartTime: bigint;
    matchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalMatchFinalizedEvent {
  export type InputTuple = [
    matchAddress: AddressLike,
    winningTeam: BigNumberish,
    team1TotalETH: BigNumberish,
    team2TotalETH: BigNumberish,
    totalPrizePool: BigNumberish
  ];
  export type OutputTuple = [
    matchAddress: string,
    winningTeam: bigint,
    team1TotalETH: bigint,
    team2TotalETH: bigint,
    totalPrizePool: bigint
  ];
  export interface OutputObject {
    matchAddress: string;
    winningTeam: bigint;
    team1TotalETH: bigint;
    team2TotalETH: bigint;
    totalPrizePool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalPlatformFeeTransferredEvent {
  export type InputTuple = [
    matchAddress: AddressLike,
    platformAddress: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    matchAddress: string,
    platformAddress: string,
    amount: bigint
  ];
  export interface OutputObject {
    matchAddress: string;
    platformAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalVotePlacedEvent {
  export type InputTuple = [
    matchAddress: AddressLike,
    voter: AddressLike,
    teamIndex: BigNumberish,
    voteCount: BigNumberish,
    totalCost: BigNumberish,
    platformFee: BigNumberish,
    prizePoolAmount: BigNumberish
  ];
  export type OutputTuple = [
    matchAddress: string,
    voter: string,
    teamIndex: bigint,
    voteCount: bigint,
    totalCost: bigint,
    platformFee: bigint,
    prizePoolAmount: bigint
  ];
  export interface OutputObject {
    matchAddress: string;
    voter: string;
    teamIndex: bigint;
    voteCount: bigint;
    totalCost: bigint;
    platformFee: bigint;
    prizePoolAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalWinningsWithdrawnEvent {
  export type InputTuple = [
    matchAddress: AddressLike,
    voter: AddressLike,
    amount: BigNumberish,
    voteCount: BigNumberish
  ];
  export type OutputTuple = [
    matchAddress: string,
    voter: string,
    amount: bigint,
    voteCount: bigint
  ];
  export interface OutputObject {
    matchAddress: string;
    voter: string;
    amount: bigint;
    voteCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchAuthorizedEvent {
  export type InputTuple = [matchAddress: AddressLike];
  export type OutputTuple = [matchAddress: string];
  export interface OutputObject {
    matchAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchDeauthorizedEvent {
  export type InputTuple = [matchAddress: AddressLike];
  export type OutputTuple = [matchAddress: string];
  export interface OutputObject {
    matchAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IWorldCupEventHub extends BaseContract {
  connect(runner?: ContractRunner | null): IWorldCupEventHub;
  waitForDeployment(): Promise<this>;

  interface: IWorldCupEventHubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allMatches: TypedContractMethod<[index: BigNumberish], [string], "view">;

  authorizeMatch: TypedContractMethod<
    [matchAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedMatches: TypedContractMethod<
    [matchAddress: AddressLike],
    [boolean],
    "view"
  >;

  deauthorizeMatch: TypedContractMethod<
    [matchAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getAllMatches: TypedContractMethod<[], [string[]], "view">;

  getMatchCount: TypedContractMethod<[], [bigint], "view">;

  isAuthorized: TypedContractMethod<
    [matchAddress: AddressLike],
    [boolean],
    "view"
  >;

  logMatchCreated: TypedContractMethod<
    [team1Name: string, team2Name: string, matchStartTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  logMatchFinalized: TypedContractMethod<
    [
      winningTeam: BigNumberish,
      team1TotalETH: BigNumberish,
      team2TotalETH: BigNumberish,
      totalPrizePool: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  logPlatformFeeTransferred: TypedContractMethod<
    [platformAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  logVotePlaced: TypedContractMethod<
    [
      voter: AddressLike,
      teamIndex: BigNumberish,
      voteCount: BigNumberish,
      totalCost: BigNumberish,
      platformFee: BigNumberish,
      prizePoolAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  logWinningsWithdrawn: TypedContractMethod<
    [voter: AddressLike, amount: BigNumberish, voteCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allMatches"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeMatch"
  ): TypedContractMethod<[matchAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedMatches"
  ): TypedContractMethod<[matchAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deauthorizeMatch"
  ): TypedContractMethod<[matchAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllMatches"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMatchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<[matchAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "logMatchCreated"
  ): TypedContractMethod<
    [team1Name: string, team2Name: string, matchStartTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logMatchFinalized"
  ): TypedContractMethod<
    [
      winningTeam: BigNumberish,
      team1TotalETH: BigNumberish,
      team2TotalETH: BigNumberish,
      totalPrizePool: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logPlatformFeeTransferred"
  ): TypedContractMethod<
    [platformAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logVotePlaced"
  ): TypedContractMethod<
    [
      voter: AddressLike,
      teamIndex: BigNumberish,
      voteCount: BigNumberish,
      totalCost: BigNumberish,
      platformFee: BigNumberish,
      prizePoolAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logWinningsWithdrawn"
  ): TypedContractMethod<
    [voter: AddressLike, amount: BigNumberish, voteCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GlobalMatchCreated"
  ): TypedContractEvent<
    GlobalMatchCreatedEvent.InputTuple,
    GlobalMatchCreatedEvent.OutputTuple,
    GlobalMatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GlobalMatchFinalized"
  ): TypedContractEvent<
    GlobalMatchFinalizedEvent.InputTuple,
    GlobalMatchFinalizedEvent.OutputTuple,
    GlobalMatchFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "GlobalPlatformFeeTransferred"
  ): TypedContractEvent<
    GlobalPlatformFeeTransferredEvent.InputTuple,
    GlobalPlatformFeeTransferredEvent.OutputTuple,
    GlobalPlatformFeeTransferredEvent.OutputObject
  >;
  getEvent(
    key: "GlobalVotePlaced"
  ): TypedContractEvent<
    GlobalVotePlacedEvent.InputTuple,
    GlobalVotePlacedEvent.OutputTuple,
    GlobalVotePlacedEvent.OutputObject
  >;
  getEvent(
    key: "GlobalWinningsWithdrawn"
  ): TypedContractEvent<
    GlobalWinningsWithdrawnEvent.InputTuple,
    GlobalWinningsWithdrawnEvent.OutputTuple,
    GlobalWinningsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MatchAuthorized"
  ): TypedContractEvent<
    MatchAuthorizedEvent.InputTuple,
    MatchAuthorizedEvent.OutputTuple,
    MatchAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "MatchDeauthorized"
  ): TypedContractEvent<
    MatchDeauthorizedEvent.InputTuple,
    MatchDeauthorizedEvent.OutputTuple,
    MatchDeauthorizedEvent.OutputObject
  >;

  filters: {
    "GlobalMatchCreated(address,string,string,uint256,uint256)": TypedContractEvent<
      GlobalMatchCreatedEvent.InputTuple,
      GlobalMatchCreatedEvent.OutputTuple,
      GlobalMatchCreatedEvent.OutputObject
    >;
    GlobalMatchCreated: TypedContractEvent<
      GlobalMatchCreatedEvent.InputTuple,
      GlobalMatchCreatedEvent.OutputTuple,
      GlobalMatchCreatedEvent.OutputObject
    >;

    "GlobalMatchFinalized(address,uint8,uint256,uint256,uint256)": TypedContractEvent<
      GlobalMatchFinalizedEvent.InputTuple,
      GlobalMatchFinalizedEvent.OutputTuple,
      GlobalMatchFinalizedEvent.OutputObject
    >;
    GlobalMatchFinalized: TypedContractEvent<
      GlobalMatchFinalizedEvent.InputTuple,
      GlobalMatchFinalizedEvent.OutputTuple,
      GlobalMatchFinalizedEvent.OutputObject
    >;

    "GlobalPlatformFeeTransferred(address,address,uint256)": TypedContractEvent<
      GlobalPlatformFeeTransferredEvent.InputTuple,
      GlobalPlatformFeeTransferredEvent.OutputTuple,
      GlobalPlatformFeeTransferredEvent.OutputObject
    >;
    GlobalPlatformFeeTransferred: TypedContractEvent<
      GlobalPlatformFeeTransferredEvent.InputTuple,
      GlobalPlatformFeeTransferredEvent.OutputTuple,
      GlobalPlatformFeeTransferredEvent.OutputObject
    >;

    "GlobalVotePlaced(address,address,uint8,uint256,uint256,uint256,uint256)": TypedContractEvent<
      GlobalVotePlacedEvent.InputTuple,
      GlobalVotePlacedEvent.OutputTuple,
      GlobalVotePlacedEvent.OutputObject
    >;
    GlobalVotePlaced: TypedContractEvent<
      GlobalVotePlacedEvent.InputTuple,
      GlobalVotePlacedEvent.OutputTuple,
      GlobalVotePlacedEvent.OutputObject
    >;

    "GlobalWinningsWithdrawn(address,address,uint256,uint256)": TypedContractEvent<
      GlobalWinningsWithdrawnEvent.InputTuple,
      GlobalWinningsWithdrawnEvent.OutputTuple,
      GlobalWinningsWithdrawnEvent.OutputObject
    >;
    GlobalWinningsWithdrawn: TypedContractEvent<
      GlobalWinningsWithdrawnEvent.InputTuple,
      GlobalWinningsWithdrawnEvent.OutputTuple,
      GlobalWinningsWithdrawnEvent.OutputObject
    >;

    "MatchAuthorized(address)": TypedContractEvent<
      MatchAuthorizedEvent.InputTuple,
      MatchAuthorizedEvent.OutputTuple,
      MatchAuthorizedEvent.OutputObject
    >;
    MatchAuthorized: TypedContractEvent<
      MatchAuthorizedEvent.InputTuple,
      MatchAuthorizedEvent.OutputTuple,
      MatchAuthorizedEvent.OutputObject
    >;

    "MatchDeauthorized(address)": TypedContractEvent<
      MatchDeauthorizedEvent.InputTuple,
      MatchDeauthorizedEvent.OutputTuple,
      MatchDeauthorizedEvent.OutputObject
    >;
    MatchDeauthorized: TypedContractEvent<
      MatchDeauthorizedEvent.InputTuple,
      MatchDeauthorizedEvent.OutputTuple,
      MatchDeauthorizedEvent.OutputObject
    >;
  };
}
