/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWorldCupEventHub__factory } from "./IWorldCupEventHub__factory";
export { IWorldCupMatch__factory } from "./IWorldCupMatch__factory";
export { IWorldCupQualification__factory } from "./IWorldCupQualification__factory";
