/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWorldCupMatch,
  IWorldCupMatchInterface,
} from "../../../contracts/interfaces/IWorldCupMatch";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint8",
        name: "winningTeam",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "team1Total",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "team2Total",
        type: "uint256",
      },
    ],
    name: "MatchFinalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "platform",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PlatformFeeTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "voteCount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalCost",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "platformFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "prizePoolAmount",
        type: "uint256",
      },
    ],
    name: "VotesPlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "voteCount",
        type: "uint256",
      },
    ],
    name: "WinningsWithdrawn",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
    ],
    name: "calculateVotePrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "atVoteCount",
        type: "uint256",
      },
    ],
    name: "calculateVotePriceAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
    ],
    name: "calculateWinnings",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentPhase",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMatchDetails",
    outputs: [
      {
        internalType: "string",
        name: "_team1Name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_team2Name",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_team1Votes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_team2Votes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_team1ETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_team2ETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_totalPrizePool",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_totalPlatformFees",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "_currentPhase",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "_isFinalized",
        type: "bool",
      },
      {
        internalType: "string",
        name: "_winner",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPhase1Details",
    outputs: [
      {
        internalType: "uint256",
        name: "team1Votes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "team2Votes",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "ended",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalPrizePool",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserVoteStats",
    outputs: [
      {
        internalType: "uint256",
        name: "team1Votes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "team2Votes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "team1ETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "team2ETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "potentialWinnings",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getVoterCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "matchEndTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "matchFinalized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "matchStartTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFeePercent",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "team1Name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "team1TotalETH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "team1VoteCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "team2Name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "team2TotalETH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "team2VoteCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalPlatformFeesCollected",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
    ],
    name: "userETH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
    ],
    name: "userVoteCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "numVotes",
        type: "uint256",
      },
    ],
    name: "vote",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "votingEndTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "winningTeam",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawWinnings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWorldCupMatch__factory {
  static readonly abi = _abi;
  static createInterface(): IWorldCupMatchInterface {
    return new Interface(_abi) as IWorldCupMatchInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWorldCupMatch {
    return new Contract(address, _abi, runner) as unknown as IWorldCupMatch;
  }
}
