/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWorldCupEventHub,
  IWorldCupEventHubInterface,
} from "../../../contracts/interfaces/IWorldCupEventHub";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "team1Name",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "team2Name",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "matchStartTime",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
    ],
    name: "GlobalMatchCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint8",
        name: "winningTeam",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "team1TotalETH",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "team2TotalETH",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalPrizePool",
        type: "uint256",
      },
    ],
    name: "GlobalMatchFinalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "platformAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "GlobalPlatformFeeTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "voteCount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalCost",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "platformFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "prizePoolAmount",
        type: "uint256",
      },
    ],
    name: "GlobalVotePlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "voteCount",
        type: "uint256",
      },
    ],
    name: "GlobalWinningsWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
    ],
    name: "MatchAuthorized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
    ],
    name: "MatchDeauthorized",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "allMatches",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
    ],
    name: "authorizeMatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
    ],
    name: "authorizedMatches",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
    ],
    name: "deauthorizeMatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllMatches",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMatchCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
    ],
    name: "isAuthorized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "team1Name",
        type: "string",
      },
      {
        internalType: "string",
        name: "team2Name",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "matchStartTime",
        type: "uint256",
      },
    ],
    name: "logMatchCreated",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "winningTeam",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "team1TotalETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "team2TotalETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalPrizePool",
        type: "uint256",
      },
    ],
    name: "logMatchFinalized",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "platformAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "logPlatformFeeTransferred",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "voteCount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalCost",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "platformFee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "prizePoolAmount",
        type: "uint256",
      },
    ],
    name: "logVotePlaced",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "voteCount",
        type: "uint256",
      },
    ],
    name: "logWinningsWithdrawn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWorldCupEventHub__factory {
  static readonly abi = _abi;
  static createInterface(): IWorldCupEventHubInterface {
    return new Interface(_abi) as IWorldCupEventHubInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWorldCupEventHub {
    return new Contract(address, _abi, runner) as unknown as IWorldCupEventHub;
  }
}
