export const WORLD_CUP_QUALIFICATION_ABI = [
  {
    inputs: [
      { internalType: "uint256", name: "_qualificationEndTime", type: "uint256" },
      { internalType: "uint8", name: "_qualificationSpots", type: "uint8" },
      { internalType: "address", name: "_platformAddress", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "voter", type: "address" },
      { indexed: true, internalType: "string", name: "countryCode", type: "string" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "voteCount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "VotePlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "string[]", name: "qualifiedCountries", type: "string[]" },
      { indexed: false, internalType: "uint256", name: "totalPrizePool", type: "uint256" },
    ],
    name: "QualificationFinalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" }],
    name: "PlatformFeeWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "voter", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "WinningsWithdrawn",
    type: "event",
  },
  {
    inputs: [],
    name: "BASE_PRICE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRICE_INCREMENT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "countryCode", type: "string" },
      { internalType: "uint256", name: "voteCount", type: "uint256" },
    ],
    name: "calculateVotePrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "countryCode", type: "string" }],
    name: "getCurrentVotePrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "countryCode", type: "string" }],
    name: "getCountryVotes",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getQualificationDetails",
    outputs: [
      { internalType: "uint256", name: "_totalPrizePool", type: "uint256" },
      { internalType: "uint256", name: "_qualificationEndTime", type: "uint256" },
      { internalType: "uint8", name: "_qualificationSpots", type: "uint8" },
      { internalType: "bool", name: "_isFinalized", type: "bool" },
      { internalType: "uint256", name: "_totalVoters", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTopCountries",
    outputs: [
      { internalType: "string[]", name: "countryCodes", type: "string[]" },
      { internalType: "uint256[]", name: "votes", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "voter", type: "address" }],
    name: "getUserVotes",
    outputs: [
      { internalType: "string[]", name: "countryCodes", type: "string[]" },
      { internalType: "uint256[]", name: "voteAmounts", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "countryCode", type: "string" },
      { internalType: "uint256", name: "voteCount", type: "uint256" },
    ],
    name: "vote",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "finalizeQualification",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "voter", type: "address" }],
    name: "calculateWinnings",
    outputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawWinnings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawPlatformFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "qualificationFinalized",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalPrizePool",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "qualificationEndTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "qualificationSpots",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
] as const
