/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWorldCupMatchAttack,
  IWorldCupMatchAttackInterface,
} from "../../../../contracts/test/ReentrancyAttacker.sol/IWorldCupMatchAttack";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "numVotes",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "referrer",
        type: "address",
      },
    ],
    name: "vote",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawWinnings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWorldCupMatchAttack__factory {
  static readonly abi = _abi;
  static createInterface(): IWorldCupMatchAttackInterface {
    return new Interface(_abi) as IWorldCupMatchAttackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWorldCupMatchAttack {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IWorldCupMatchAttack;
  }
}
