/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ReentrancyAttacker,
  ReentrancyAttackerInterface,
} from "../../../../contracts/test/ReentrancyAttacker.sol/ReentrancyAttacker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "numVotes",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "referrer",
        type: "address",
      },
    ],
    name: "attack_vote",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "attack_withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "attacking",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "target",
    outputs: [
      {
        internalType: "contract IWorldCupMatchAttack",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161035938038061035983398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b6102c6806100936000396000f3fe6080604052600436106100435760003560e01c80633c0bbcd9146100c55780635405a114146100fb5780638ef092671461010e578063d4b839921461012357600080fd5b366100c057600054600160a01b900460ff16156100be576000805460ff60a01b198116825560408051636621741d60e11b815290516001600160a01b039092169263cc42e83a9260048084019382900301818387803b1580156100a557600080fd5b505af11580156100b9573d6000803e3d6000fd5b505050505b005b600080fd5b3480156100d157600080fd5b506000546100e690600160a01b900460ff1681565b60405190151581526020015b60405180910390f35b6100be61010936600461023c565b61015b565b34801561011a57600080fd5b506100be6101d1565b34801561012f57600080fd5b50600054610143906001600160a01b031681565b6040516001600160a01b0390911681526020016100f2565b60005460405163082606b160e21b815260ff85166004820152602481018490526001600160a01b038381166044830152909116906320981ac49034906064016000604051808303818588803b1580156101b357600080fd5b505af11580156101c7573d6000803e3d6000fd5b5050505050505050565b6000805460ff60a01b198116600160a01b17825560408051636621741d60e11b815290516001600160a01b039092169263cc42e83a9260048084019382900301818387803b15801561022257600080fd5b505af1158015610236573d6000803e3d6000fd5b50505050565b60008060006060848603121561025157600080fd5b833560ff8116811461026257600080fd5b92506020840135915060408401356001600160a01b038116811461028557600080fd5b80915050925092509256fea2646970667358221220b9833605e8d8871963fdfa87955c9847527d6d27b2c235a55111b735231602c464736f6c63430008140033";

type ReentrancyAttackerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrancyAttackerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrancyAttacker__factory extends ContractFactory {
  constructor(...args: ReentrancyAttackerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _target: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_target, overrides || {});
  }
  override deploy(
    _target: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_target, overrides || {}) as Promise<
      ReentrancyAttacker & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReentrancyAttacker__factory {
    return super.connect(runner) as ReentrancyAttacker__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyAttackerInterface {
    return new Interface(_abi) as ReentrancyAttackerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrancyAttacker {
    return new Contract(address, _abi, runner) as unknown as ReentrancyAttacker;
  }
}
