/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IWorldCupMatchAttack } from "./IWorldCupMatchAttack";
export type { ReentrancyAttacker } from "./ReentrancyAttacker";
