/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWorldCupEventHub__factory } from "./IWorldCupEventHub__factory";
export { WorldCupMatch__factory } from "./WorldCupMatch__factory";
