/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWorldCupEventHub,
  IWorldCupEventHubInterface,
} from "../../../contracts/WorldCupMatch.sol/IWorldCupEventHub";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "team1Name",
        type: "string",
      },
      {
        internalType: "string",
        name: "team2Name",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "matchStartTime",
        type: "uint256",
      },
    ],
    name: "logMatchCreated",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "winningTeam",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "team1TotalETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "team2TotalETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalPrizePool",
        type: "uint256",
      },
    ],
    name: "logMatchFinalized",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "platformAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "logPlatformFeeTransferred",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "teamIndex",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "voteCount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalCost",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "platformFee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "prizePoolAmount",
        type: "uint256",
      },
    ],
    name: "logVotePlaced",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "voteCount",
        type: "uint256",
      },
    ],
    name: "logWinningsWithdrawn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWorldCupEventHub__factory {
  static readonly abi = _abi;
  static createInterface(): IWorldCupEventHubInterface {
    return new Interface(_abi) as IWorldCupEventHubInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWorldCupEventHub {
    return new Contract(address, _abi, runner) as unknown as IWorldCupEventHub;
  }
}
