/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEventHubFactory,
  IEventHubFactoryInterface,
} from "../../../contracts/WorldCupMatchFactory.sol/IEventHubFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "matchAddress",
        type: "address",
      },
    ],
    name: "authorizeMatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEventHubFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IEventHubFactoryInterface {
    return new Interface(_abi) as IEventHubFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEventHubFactory {
    return new Contract(address, _abi, runner) as unknown as IEventHubFactory;
  }
}
