/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IEventHubFactory__factory } from "./IEventHubFactory__factory";
export { WorldCupMatchFactory__factory } from "./WorldCupMatchFactory__factory";
