/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IEventHubFactory } from "./IEventHubFactory";
export type { WorldCupMatchFactory } from "./WorldCupMatchFactory";
