/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface WorldCupMatchFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_FEE_PERCENT"
      | "createMatch"
      | "deployedMatches"
      | "eventHub"
      | "getDeployedMatches"
      | "getMatchCount"
      | "owner"
      | "platformAddress"
      | "platformFeePercent"
      | "renounceOwnership"
      | "setPlatformAddress"
      | "setPlatformFee"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchCreated"
      | "OwnershipTransferred"
      | "PlatformAddressUpdated"
      | "PlatformFeeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createMatch",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedMatches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "eventHub", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDeployedMatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eventHub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchAddress: AddressLike,
    team1Name: string,
    team2Name: string,
    deployTime: BigNumberish
  ];
  export type OutputTuple = [
    matchAddress: string,
    team1Name: string,
    team2Name: string,
    deployTime: bigint
  ];
  export interface OutputObject {
    matchAddress: string;
    team1Name: string;
    team2Name: string;
    deployTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformAddressUpdatedEvent {
  export type InputTuple = [newPlatform: AddressLike];
  export type OutputTuple = [newPlatform: string];
  export interface OutputObject {
    newPlatform: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFeePercent: BigNumberish];
  export type OutputTuple = [newFeePercent: bigint];
  export interface OutputObject {
    newFeePercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorldCupMatchFactory extends BaseContract {
  connect(runner?: ContractRunner | null): WorldCupMatchFactory;
  waitForDeployment(): Promise<this>;

  interface: WorldCupMatchFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  createMatch: TypedContractMethod<
    [team1Name: string, team2Name: string, deployTime: BigNumberish],
    [string],
    "nonpayable"
  >;

  deployedMatches: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  eventHub: TypedContractMethod<[], [string], "view">;

  getDeployedMatches: TypedContractMethod<[], [string[]], "view">;

  getMatchCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformAddress: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPlatformAddress: TypedContractMethod<
    [_platformAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_platformFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<
    [team1Name: string, team2Name: string, deployTime: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployedMatches"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "eventHub"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDeployedMatches"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMatchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformAddress"
  ): TypedContractMethod<[_platformAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<
    [_platformFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformAddressUpdated"
  ): TypedContractEvent<
    PlatformAddressUpdatedEvent.InputTuple,
    PlatformAddressUpdatedEvent.OutputTuple,
    PlatformAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;

  filters: {
    "MatchCreated(address,string,string,uint256)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformAddressUpdated(address)": TypedContractEvent<
      PlatformAddressUpdatedEvent.InputTuple,
      PlatformAddressUpdatedEvent.OutputTuple,
      PlatformAddressUpdatedEvent.OutputObject
    >;
    PlatformAddressUpdated: TypedContractEvent<
      PlatformAddressUpdatedEvent.InputTuple,
      PlatformAddressUpdatedEvent.OutputTuple,
      PlatformAddressUpdatedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
  };
}
